export type FacultyMember = {
  name: string;
  designation: string;
  department: string;
  color: "plum" | "sage" | "pomegranate" | "turmeric" | "saffron" | "basil";
  summary: string;
  profile?: string;
  qualifications?: string;
  email?: string;
  telephone?: string;
  professionalPages?: { label: string; url: string }[];
  teachingAreas?: string[];
  researchInterests?: string[];
  currentPhDSupervision?: string[];
  currentResearchProjects?: string[];
};

export const FACULTY: FacultyMember[] = [
  {
    name: "Dr. M Srijaya",
    designation: "Associate Professor & Head",
    department: "Food & Nutritional Sciences",
    color: "plum",
    summary: "Head of Food & Nutritional Sciences focusing on food processing, preservation and applied nutrition.",
    qualifications: "M.Sc., Ph.D.",
    email: "msrijaya@sssihl.edu.in",
    telephone: "+91 8554 272567",
    professionalPages: [
      { label: "LinkedIn", url: "https://www.linkedin.com/in/srijaya-mupparapu-39036a17" },
      { label: "ResearchGate", url: "https://www.researchgate.net/profile/Srijaya_Mupparapu" },
    ],
    profile: "Dr. (Mrs.) M Srijaya pursued her Bachelors in Home Science and Masters in Food Science and Nutrition from Sri Sathya Sai Institute of Higher Learning. She then joined the department as a lecturer in 1996 and completed her Ph.D. in Food Technology from Sri Venkateswara University, Tirupathi. She currently leads the Department of Food & Nutritional Sciences at SSSIHL.",
    teachingAreas: [
      "Food Chemistry",
      "Food Processing and Preservation",
      "Fruit and Vegetable Technology",
      "Food safety and quality assurance",
      "Women Nutrition",
      "Paediatric and Geriatric Nutrition",
    ],
    researchInterests: [
      "Food irradiation for preservation of fruits and vegetables",
      "Dairy science",
      "Quality and nutrition indicators of food products",
      "Phytochemical profiling of organic fruits and vegetables",
      "Optimization of technologies for transport and storage of organic produce",
    ],
    currentPhDSupervision: [
      "Ms. Alisha Pradhan (Postharvest Management of Fruits and Vegetables)",
      "Ms. Beesetti Lohita (Novel technological approaches for processing of functional dairy products)",
      "Ms. Deepika Shrestha (Dairy Science & Technology)",
    ],
  },
  {
    name: "Prof. N Uday Kiran",
    designation: "Professor & Head",
    department: "Mathematics & Computer Science",
    color: "sage",
    summary: "Head of Mathematics & Computer Science with a focus on academic leadership and cross-disciplinary education.",
  },
  {
    name: "Dr. K Vijay Sai",
    designation: "Associate Professor & Head",
    department: "Physics",
    color: "pomegranate",
    summary: "Physics academic leader guiding laboratory instruction and applied physical science research.",
  },
  {
    name: "Dr. G Raghavender Raju",
    designation: "Associate Professor, Head & Dean of Student Welfare",
    department: "Economics",
    color: "turmeric",
    summary: "Leads student welfare and economics education with a strong student-centred approach.",
  },
  {
    name: "Dr. P Lavanya",
    designation: "Associate Professor & Head",
    department: "Education",
    color: "saffron",
    summary: "Head of Education, responsible for teacher education and curriculum development.",
  },
  {
    name: "Dr. Sripada Lakshminath",
    designation: "Associate Professor & Head",
    department: "Chemistry",
    color: "basil",
    summary: "Chemistry head driving foundational and applied chemical sciences instruction.",
  },
  {
    name: "Dr. Maitali Khanna",
    designation: "Asst. Professor & Head",
    department: "Languages & Literature",
    color: "plum",
    summary: "Leads Languages & Literature with emphasis on literary studies and communication.",
  },
  {
    name: "Sri S Sai Ram",
    designation: "Asst. Professor (Tabla) and Head (In-charge)",
    department: "Performing Arts",
    color: "sage",
    summary: "Tabla specialist leading practical music training and performing arts mentorship.",
  },
  {
    name: "Prof. S Venketesh",
    designation: "Professor & Head",
    department: "Biosciences",
    color: "pomegranate",
    summary: "Heads Biosciences with a focus on life science teaching, research and laboratory training.",
  },
  {
    name: "Prof. G Nageswara Rao",
    designation: "Professor (Hon.)",
    department: "Chemistry",
    color: "turmeric",
    summary: "Honorary Chemistry professor providing senior scientific mentorship.",
  },
  {
    name: "Prof. N Sivakumar",
    designation: "Professor & Dean of Management & Commerce",
    department: "Management & Commerce",
    color: "saffron",
    summary: "Leads the Management & Commerce faculty and supports business education programs.",
  },
  {
    name: "Dr. U Suma",
    designation: "Associate Professor",
    department: "Management & Commerce",
    color: "basil",
    summary: "Management faculty member teaching commerce and business studies.",
  },
  {
    name: "Dr. Sayee Manohar K",
    designation: "Associate Professor",
    department: "Management & Commerce",
    color: "plum",
    summary: "Associate professor in commerce with expertise in management education.",
  },
  {
    name: "Prof. N Srividya",
    designation: "Professor & Dean of Sciences",
    department: "Food & Nutritional Sciences",
    color: "sage",
    summary: "Dean of Sciences and active researcher in food science and nutrition.",
    qualifications: "M.Sc., Ph.D.",
    email: "nsrividya@sssihl.edu.in",
    telephone: "+91 8554 272567",
    professionalPages: [
      { label: "LinkedIn", url: "https://www.linkedin.com/in/dr-ms-n-srividya-sssihl-045443a2/?trk=public-profile-join-page" },
      { label: "ResearchGate", url: "https://www.researchgate.net/profile/Srividya_Nagarajan" },
      { label: "Google Scholar", url: "https://scholar.google.com/citations?user=-wjL4ocAAAAJ&hl=en&oi=sra" },
    ],
    profile: "Prof. N. Srividya is an active researcher in Food Science and Nutrition with over 25 years of teaching and research experience at SSSIHL. She has guided Ph.D. scholars and overseen ICMR-funded and UGC-DAE-funded research projects. She has served as Director of the Anantapur Campus and currently leads as Dean, Faculty of Sciences.",
    teachingAreas: [
      "Public Health",
      "Clinical and Ayurvedic Nutrition",
      "Postharvest technology",
      "Food Microbiology and Safety",
      "Functional Foods and Nutraceuticals",
      "Culinary science and Food Chemistry",
    ],
    researchInterests: [
      "Nutrient and nutraceutical profiling of indigenous food crops",
      "Food bioprocesses for micronutrient malnutrition",
      "Nutritional biology of diabetes",
      "Aloe vera and chitosan biopolymer applications",
      "Industry-based functional food technologies",
    ],
    currentPhDSupervision: [
      "Ms. Shrijana Rasaily (Therapeutic and bioactivity assessment of functional foods)",
      "Ms. Sai Sruthi Shree K K (Nutritional Profiling of Food Materials)",
      "Ms. Mounika Pandey",
    ],
    currentResearchProjects: [
      "Antidiabetic evaluation of Indian pigmented rice varieties — ICMR, ₹24 Lakhs (2019-2022)",
      "XRF profiling of essential minerals in native and bio-processed pigmented rice varieties — UGC-DAE-Consortium (2019-2020)",
    ],
  },
  {
    name: "Prof. Pallav Kumar Baruah",
    designation: "Senior Professor & Dean of Innovation & Entrepreneurship",
    department: "Mathematics & Computer Science",
    color: "pomegranate",
    summary: "Innovation and entrepreneurship leader bridging applied science and startup mentoring.",
  },
  {
    name: "Prof. R Raghunatha Sarma",
    designation: "Professor",
    department: "Mathematics & Computer Science",
    color: "turmeric",
    summary: "Mathematics professor contributing to computational science education.",
  },
  {
    name: "Prof. B Andallu",
    designation: "Professor (Hon.)",
    department: "Food & Nutritional Sciences",
    color: "saffron",
    summary: "Honorary biochemist and phytochemical researcher with deep expertise in natural product science.",
    qualifications: "M.Sc., Ph.D.",
    email: "bandallu@sssihl.edu.in",
    telephone: "+91 8554 272567",
    professionalPages: [
      { label: "LinkedIn", url: "https://www.linkedin.com/in/prof-bondada-andallu-bb21967b/" },
      { label: "ResearchGate", url: "https://www.researchgate.net/profile/Bondada_Andallu" },
      { label: "Google Scholar", url: "https://scholar.google.com/citations?hl=en&user=8LRN8QQAAAAJ" },
    ],
    profile: "Prof. B. Andallu is a biochemist with expertise in natural product isolation and bioactivity assessment. She has published extensively on natural remedies for oxidative stress-induced conditions and served as an editorial board member and journal reviewer. She has taught for over three decades and guided more than 50 postgraduate and doctoral dissertations.",
    teachingAreas: [
      "Biomacromolecules and Metabolism",
      "Analytical Techniques",
      "Nutritional Biochemistry",
      "Clinical Biochemistry",
    ],
    researchInterests: [
      "Phytochemical antioxidant and anti-inflammatory research",
      "Screening natural remedies for diabetes, arthritis and cancer",
      "Scientific validation of traditional herbs by reverse pharmacology",
    ],
  },
  {
    name: "Prof. S Balasubramanian",
    designation: "Professor",
    department: "Mathematics & Computer Science",
    color: "basil",
    summary: "Mathematics professor contributing to core theory and applied computation.",
  },
  {
    name: "Prof. Gowrishankar R",
    designation: "Professor & Dean of Academic Affairs",
    department: "Physics",
    color: "plum",
    summary: "Academic affairs dean with a physics background and administrative leadership role.",
  },
  {
    name: "Prof. Deepa Seetharaman",
    designation: "Professor",
    department: "Physics",
    color: "sage",
    summary: "Physics faculty focused on research-based science education.",
  },
  {
    name: "Prof. R Prabhakara Rao",
    designation: "Professor (Hon.)",
    department: "Economics",
    color: "pomegranate",
    summary: "Honorary economics professor providing senior advisory and teaching support.",
  },
  {
    name: "Dr. Priyam Chaturvedi",
    designation: "Asst. Professor (Hindustani Vocal)",
    department: "Performing Arts",
    color: "turmeric",
    summary: "Hindustani vocal faculty teaching Indian classical vocal music.",
  },
  {
    name: "Prof. Madhu Kapani",
    designation: "Professor (Hon.)",
    department: "Education",
    color: "saffron",
    summary: "Honorary education professor with experience in academic leadership and pedagogy.",
  },
  {
    name: "Prof. Rani P L",
    designation: "Professor & Dean of Humanities & Social Sciences, Languages & Literature",
    department: "English Language & Literature",
    color: "basil",
    summary: "Dean of Humanities guiding language, literature and social science curricula.",
  },
  {
    name: "Dr. Vivek Chauhan",
    designation: "Associate Professor",
    department: "English Language & Literature",
    color: "plum",
    summary: "English faculty focused on literature, composition and academic communication.",
  },
  {
    name: "Prof. C N Sundaresan",
    designation: "Professor (Hon.)",
    department: "Chemistry",
    color: "sage",
    summary: "Honorary chemistry professor supporting the department through senior mentorship.",
  },
  {
    name: "Prof. Rajni Bhandari",
    designation: "Professor",
    department: "Chemistry",
    color: "pomegranate",
    summary: "Chemistry professor teaching foundational and applied chemical sciences.",
  },
  {
    name: "Dr. Isha Sai",
    designation: "Associate Professor",
    department: "Biosciences",
    color: "turmeric",
    summary: "Biosciences faculty contributing to life science teaching and research.",
  },
  {
    name: "Prof. R Gangadhara Sastry",
    designation: "Professor (Hon.)",
    department: "Political Science",
    color: "saffron",
    summary: "Honorary political science professor providing expert instruction in governance and policy.",
  },
  {
    name: "Prof. M Praphulla",
    designation: "Professor (Hon.)",
    department: "Telugu Language & Literature",
    color: "basil",
    summary: "Honorary Telugu language and literature professor with deep literary expertise.",
  },
  {
    name: "Dr. Kiron Bala Arora",
    designation: "Associate Professor (Hon.)",
    department: "Hindi",
    color: "plum",
    summary: "Honorary Hindi faculty focused on language, literature and cultural studies.",
  },
  {
    name: "Dr. N Venkatesha Rao",
    designation: "Associate Professor (Hon.)",
    department: "Sanskrit",
    color: "sage",
    summary: "Honorary Sanskrit professor preserving classical language and texts.",
  },
  {
    name: "Dr. Rita Gupta",
    designation: "Associate Professor (Hon.)",
    department: "Mathematics & Computer Science",
    color: "pomegranate",
    summary: "Honorary faculty in mathematics and computer science with broad academic impact.",
  },
  {
    name: "Dr. Y Lakshmi Naidu",
    designation: "Associate Professor",
    department: "Mathematics & Computer Science",
    color: "turmeric",
    summary: "Mathematics faculty teaching applied analytics and computation.",
  },
  {
    name: "Sri B Venkatramana",
    designation: "Asst. Professor",
    department: "Mathematics & Computer Science",
    color: "saffron",
    summary: "Assistant professor supporting mathematics and computing coursework.",
  },
  {
    name: "Dr. A Sumana",
    designation: "Asst. Professor",
    department: "Food & Nutritional Sciences",
    color: "basil",
    summary: "Assistant professor and applied researcher working at the interface of food safety, product development and sensory science.",
    qualifications: "M.Sc., Ph.D.",
    email: "asumana@sssihl.edu.in",
    telephone: "+91 8554 272567",
    professionalPages: [
      { label: "ResearchGate", url: "https://www.researchgate.net/profile/Araveti_Sumana" },
    ],
    profile: "Dr. A Sumana graduated from SSSIHL and joined the Institute in 2001 after clearing the NET for lectureship. She completed her doctorate in 2017 and actively conducts research in food safety, product development and nutritional epidemiology.",
    teachingAreas: [
      "Microbial Food Safety",
      "Current Issues in Food Science",
      "Food product development and evaluation",
      "Entrepreneurship and marketing",
      "Dietetics",
      "Nutrition in emergencies",
      "Bakery and Confectionery",
    ],
    researchInterests: [
      "Sensory marketing and consumer behaviour for foods",
      "Nutrition in disease prevention",
      "Novel functional foods development",
    ],
    currentPhDSupervision: [
      "Ms. Shivangi Verma (Nutritional Epidemiology)",
      "Ms. Sparsh Sumnirom Subba",
    ],
  },
  {
    name: "Sri Sanjay Sahni",
    designation: "Associate Professor",
    department: "Management & Commerce",
    color: "plum",
    summary: "Associate professor in business and management education.",
  },
  {
    name: "Sri Rajkumar Jain",
    designation: "Associate Professor (Hon.)",
    department: "Physics",
    color: "sage",
    summary: "Honorary physics professor providing senior academic mentorship.",
  },
  {
    name: "Dr. B Rudramamba",
    designation: "Associate Professor (Hon.)",
    department: "Education",
    color: "pomegranate",
    summary: "Honorary education faculty with extensive teaching experience.",
  },
  {
    name: "Dr. G Pavana Kumari",
    designation: "Associate Professor",
    department: "Chemistry",
    color: "turmeric",
    summary: "Chemistry faculty teaching and researching chemical science applications.",
  },
  {
    name: "Dr. Raja Sankaran",
    designation: "Associate Professor",
    department: "Management & Commerce",
    color: "saffron",
    summary: "Management faculty focused on commerce and business systems.",
  },
  {
    name: "Dr. J Krishna Kiran Kumar",
    designation: "Associate Professor",
    department: "Chemistry",
    color: "basil",
    summary: "Chemistry faculty specializing in academic instruction and research.",
  },
  {
    name: "Prof. B S Vijayakumar",
    designation: "Professor (Hon.)",
    department: "Biosciences",
    color: "plum",
    summary: "Honorary biosciences professor providing senior research mentorship.",
  },
  {
    name: "Dr. Vijeyakumary Vijayaratnam",
    designation: "Associate Professor (Hon.)",
    department: "Biosciences",
    color: "sage",
    summary: "Honorary biosciences professor with focus on life science teaching.",
  },
  {
    name: "Dr. A Ashok",
    designation: "Associate Professor (Hon.)",
    department: "Biosciences",
    color: "pomegranate",
    summary: "Honorary biosciences faculty supporting research and curriculum delivery.",
  },
  {
    name: "Dr. B E Pradeep",
    designation: "Associate Professor",
    department: "Biosciences",
    color: "turmeric",
    summary: "Biosciences faculty engaged in teaching and laboratory research.",
  },
  {
    name: "Dr. M Venkatalakshmi",
    designation: "Asst. Professor (Hon.)",
    department: "Philosophy",
    color: "saffron",
    summary: "Honorary philosophy faculty contributing to ethical and philosophical instruction.",
  },
  {
    name: "Dr. Kumar Sai Smaran",
    designation: "Asst. Professor",
    department: "Chemistry",
    color: "basil",
    summary: "Assistant chemistry professor teaching foundational chemical sciences.",
  },
  {
    name: "Mrs. G Yamuna Rani",
    designation: "Asst. Professor",
    department: "Telugu Language & Literature",
    color: "plum",
    summary: "Assistant professor in Telugu language and literature studies.",
  },
  {
    name: "Dr. Yadusree K P",
    designation: "Asst. Professor",
    department: "Sanskrit",
    color: "sage",
    summary: "Assistant professor teaching classical Sanskrit language and literature.",
  },
  {
    name: "Dr. Piyush Kumar Shrivastava",
    designation: "Associate Professor (Hon.)",
    department: "Hindi",
    color: "pomegranate",
    summary: "Honorary Hindi professor specializing in language and literature education.",
  },
  {
    name: "Dr. Mahabala Rao M G",
    designation: "Asst. Professor",
    department: "Sanskrit",
    color: "turmeric",
    summary: "Assistant professor of Sanskrit with a focus on classical texts.",
  },
  {
    name: "Sri R Renju",
    designation: "Information Scientist",
    department: "Management & Commerce",
    color: "saffron",
    summary: "Information scientist supporting management education through data systems.",
  },
  {
    name: "Dr. M B S S Narayana",
    designation: "Asst. Professor",
    department: "Sanskrit",
    color: "basil",
    summary: "Assistant professor teaching classical Sanskrit scholarship.",
  },
  {
    name: "Dr. N Jayaprada",
    designation: "Asst. Professor",
    department: "Management & Commerce",
    color: "plum",
    summary: "Assistant professor teaching commerce and management subjects.",
  },
  {
    name: "Dr. N Niranjan",
    designation: "Asst. Professor",
    department: "Management & Commerce",
    color: "sage",
    summary: "Assistant professor supporting business and commerce education.",
  },
  {
    name: "Dr. Subramanian S Iyer",
    designation: "Associate Professor",
    department: "Management & Commerce",
    color: "pomegranate",
    summary: "Associate professor in management and commerce with a focus on industry-ready skills.",
  },
  {
    name: "Sri Rajeev Rajan",
    designation: "Asst. Professor",
    department: "Management & Commerce",
    color: "turmeric",
    summary: "Assistant professor teaching commerce and management courses.",
  },
  {
    name: "Dr. M S Sai Vinod",
    designation: "Asst. Professor",
    department: "Management & Commerce",
    color: "saffron",
    summary: "Assistant professor in commerce with expertise in business education.",
  },
  {
    name: "Dr. Murali Ravi",
    designation: "Asst. Professor",
    department: "Physics",
    color: "basil",
    summary: "Assistant physics professor teaching experimental and theoretical physics.",
  },
  {
    name: "Ms. C Priyanka",
    designation: "Asst. Professor",
    department: "Management & Commerce",
    color: "plum",
    summary: "Assistant professor in commerce education and training.",
  },
  {
    name: "Sri S Sai Manohar",
    designation: "Asst. Professor",
    department: "Management & Commerce",
    color: "sage",
    summary: "Assistant professor in commerce supporting student development.",
  },
  {
    name: "Sri L K Prasad Rayaprolu",
    designation: "Asst. Professor",
    department: "Management & Commerce",
    color: "pomegranate",
    summary: "Assistant professor teaching management and commerce coursework.",
  },
  {
    name: "Dr. Akanksha Aggarwal",
    designation: "Asst. Professor",
    department: "Management & Commerce",
    color: "turmeric",
    summary: "Assistant professor in commerce and management education.",
  },
  {
    name: "Dr. Swetha Thiruchanuru",
    designation: "Asst. Professor",
    department: "Management & Commerce",
    color: "saffron",
    summary: "Assistant professor teaching commerce and business analytics.",
  },
  {
    name: "Mrs. Aparna V",
    designation: "Asst. Professor",
    department: "Management & Commerce",
    color: "basil",
    summary: "Assistant professor guiding commerce students and curriculum delivery.",
  },
  {
    name: "Dr. C Jayashree",
    designation: "Asst. Professor",
    department: "Management & Commerce",
    color: "plum",
    summary: "Assistant professor teaching management science and commerce.",
  },
  {
    name: "Dr. Anand Govindaluri",
    designation: "Professor of Practice",
    department: "Entrepreneurship & Innovation",
    color: "sage",
    summary: "Practitioner faculty in entrepreneurship and innovation education.",
  },
  {
    name: "Dr. P Jyothikumari",
    designation: "Asst. Professor",
    department: "Biosciences",
    color: "pomegranate",
    summary: "Assistant biosciences professor engaged in life science teaching.",
  },
  {
    name: "Dr. Pallavi C",
    designation: "Asst. Professor",
    department: "Biosciences",
    color: "turmeric",
    summary: "Assistant professor contributing to biosciences research and instruction.",
  },
  {
    name: "Dr. K N Naresh",
    designation: "Asst. Professor",
    department: "Biosciences",
    color: "saffron",
    summary: "Assistant biosciences faculty focused on biological science education.",
  },
  {
    name: "Dr. P Sujith Kumar",
    designation: "Asst. Professor",
    department: "Biosciences",
    color: "basil",
    summary: "Assistant professor in biosciences teaching laboratory and theoretical topics.",
  },
  {
    name: "Dr. Abhijith Ajayakumar",
    designation: "Asst. Professor",
    department: "Mathematics & Computer Science",
    color: "plum",
    summary: "Assistant professor teaching mathematics and computing concepts.",
  },
  {
    name: "Dr. Meera Manikkavachakan",
    designation: "Asst. Professor",
    department: "Food & Nutritional Sciences",
    color: "sage",
    summary: "Assistant professor engaged in functional food development, nutrition education and shelf-stability research.",
    qualifications: "M.Sc., Ph.D.",
    email: "meeram@sssihl.edu.in",
    telephone: "+91 8554 272567",
    professionalPages: [
      { label: "LinkedIn", url: "https://www.linkedin.com/in/meera-manikkavachakan-b59b5938/" },
      { label: "ResearchGate", url: "https://www.researchgate.net/profile/Meera_Manikkavachakan" },
    ],
    profile: "Dr. Meera Manikkavachakan joined SSSIHL in 1996 after earning her B.Sc. and M.Sc. at the Institute. She holds PG diplomas in preventive and promotive health care and geriatric care, and completed her food science doctorate from Sri Venkateswara University. Her research includes gluten-free snacks, nutrient analysis and shelf-life studies for multi-millet products.",
    teachingAreas: [
      "Public Nutrition and Epidemiology",
      "Research Methodology",
      "Food Product Development",
      "Therapeutic Nutrition and Dietetics",
    ],
    researchInterests: [
      "Gluten-free snack food formulation",
      "Shelf stability of bakery and roasted millet snacks",
      "Nutrition education models for vulnerable communities",
    ],
    currentPhDSupervision: ["Ms. Sai Dharshini S (Snack Food Technology)"],
  },
  {
    name: "Dr. Tapasya Anand",
    designation: "Asst. Professor",
    department: "Food & Nutritional Sciences",
    color: "pomegranate",
    summary: "Assistant professor researching functional foods, molecular nutrition and sports nutrition.",
    qualifications: "M.Sc., Ph.D.",
    email: "tapasyaanand@sssihl.edu.in",
    telephone: "+91 8554 272567",
    professionalPages: [
      { label: "LinkedIn", url: "https://www.linkedin.com/in/dr-tapasya-anand-5746169b/" },
      { label: "ResearchGate", url: "https://www.researchgate.net/profile/Tapasya_Anand" },
    ],
    profile: "Dr. Tapasya Anand received her B.Sc. and M.Sc. from SSSIHL and earned her doctorate in 2012. She joined the Department of Food & Nutritional Sciences in 2013 and leads research on nutritional profiling, functional product formulation for diabetics and athletes, and therapeutic potential studies.",
    teachingAreas: [
      "Functional Foods and Nutraceuticals",
      "Clinical Nutrition",
      "Molecular Nutrition",
      "Sports Nutrition",
      "Human Physiology",
      "Fermentation Technology",
    ],
    researchInterests: [
      "Phytochemical profiling of mushrooms and underutilized seeds",
      "Functional product formulation for type 2 diabetes and athletes",
      "In vitro and in vivo evaluation of therapeutic foods",
    ],
  },
  {
    name: "Dr. Ambati Padmaja",
    designation: "Asst. Professor",
    department: "Food & Nutritional Sciences",
    color: "turmeric",
    summary: "Assistant professor researching phytochemical analysis and valorisation of food processing waste.",
    qualifications: "M.Sc., Ph.D.",
    email: "ambatipadmaja@sssihl.edu.in",
    telephone: "+91 8554 272567",
    professionalPages: [
      { label: "LinkedIn", url: "https://www.linkedin.com/in/padmaja-ambati-08760b34/" },
      { label: "ResearchGate", url: "https://www.researchgate.net/profile/Padmaja_Ambati/publications" },
    ],
    profile: "Dr. Ambati Padmaja is an expert in food science, nutrition and technology, especially phytochemical analysis, food fortification and reuse of food processing waste. She completed her doctorate in 2011 and joined SSSIHL after working as a senior research fellow in national projects on oilseeds and oils.",
    teachingAreas: [
      "Food Preservation",
      "Nutrition",
      "Food Packaging",
      "Evaluation of foods",
      "Ergonomics",
      "Grain Science and Oils",
    ],
    researchInterests: [
      "Antioxidant extraction and application in edible oils",
      "Valorisation of food processing waste",
      "Natural antioxidant and active ingredient recovery",
    ],
    currentPhDSupervision: ["Ms. Katam Veera Chaitanya Bhagavathi (Valorization of Food Processing Waste)"],
  },
  {
    name: "Dr. Jhinuk Gupta",
    designation: "Asst. Professor",
    department: "Food & Nutritional Sciences",
    color: "saffron",
    summary: "Assistant professor with expertise in food chemistry, polymer chemistry and food safety.",
    qualifications: "M.Sc., Ph.D.",
    email: "jhinukgupta@sssihl.edu.in",
    telephone: "+91 8554 272567",
    professionalPages: [
      { label: "LinkedIn", url: "https://www.linkedin.com/in/jhinuk-gupta-a7070141/?originalSubdomain=in" },
      { label: "Google Scholar", url: "https://scholar.google.com/citations?user=paTfRSUAAAAJ&hl=en" },
    ],
    profile: "Dr. Jhinuk Gupta is an organic chemist with a Ph.D. from the National University of Singapore and postdoctoral experience in food science and value-added processing. She joined SSSIHL in 2019 and researches food adulteration screening, biofuels from food waste, and food chemistry applications.",
    teachingAreas: [
      "Applied Chemistry",
      "Biochemistry",
      "Food Chemistry",
      "Analytical Techniques",
    ],
    researchInterests: [
      "Screening and detection of food adulterants",
      "Biofuel production from food wastes",
    ],
    currentPhDSupervision: [
      "Ms. Amrita Shaw (Food Safety)",
      "Ms. Bezawada Sree Sesha Sravanika (Food Safety & Quality Management)",
    ],
  },
  {
    name: "Dr. N B Gayathri",
    designation: "Asst. Professor",
    department: "Mathematics & Computer Science",
    color: "basil",
    summary: "Assistant professor in mathematics and computing education.",
  },
  {
    name: "Dr. Rajiv Gurung",
    designation: "Asst. Professor",
    department: "Economics",
    color: "plum",
    summary: "Assistant professor teaching economics and public policy.",
  },
  {
    name: "Dr. Chandrahaas C S",
    designation: "Asst. Professor",
    department: "Management & Commerce",
    color: "sage",
    summary: "Assistant professor in management and commerce education.",
  },
  {
    name: "Dr. K J Srinivas",
    designation: "Asst. Professor",
    department: "Management & Commerce",
    color: "pomegranate",
    summary: "Management faculty supporting business education.",
  },
  {
    name: "Dr. Ratnakar Palakodeti",
    designation: "Professor of Practice",
    department: "Biosciences",
    color: "turmeric",
    summary: "Practice professor bringing industry-relevant biosciences knowledge.",
  },
  {
    name: "Dr. Subbarao Kanchi",
    designation: "Asst. Professor",
    department: "Physics",
    color: "saffron",
    summary: "Assistant professor in physics teaching and research.",
  },
  {
    name: "Dr. Krishna Kiran Vamsi Dasu",
    designation: "Associate Professor",
    department: "Mathematics & Computer Science",
    color: "basil",
    summary: "Associate professor teaching mathematics and computer science.",
  },
  {
    name: "Dr. Sai Shyam",
    designation: "Asst. Professor",
    department: "Mathematics & Computer Science",
    color: "plum",
    summary: "Assistant professor in mathematics and computing.",
  },
  {
    name: "Dr. V Bhaskaran",
    designation: "Asst. Professor",
    department: "Mathematics & Computer Science",
    color: "sage",
    summary: "Assistant faculty member in mathematics and computing.",
  },
  {
    name: "Dr. Swayamsiddha Kar",
    designation: "Asst. Professor",
    department: "Chemistry",
    color: "pomegranate",
    summary: "Assistant chemistry professor teaching laboratory and theoretical topics.",
  },
  {
    name: "Dr. Darshan Gera",
    designation: "Associate Professor",
    department: "Mathematics & Computer Science",
    color: "turmeric",
    summary: "Associate professor in mathematics and computer science education.",
  },
  {
    name: "Dr. Naga Sai Visweswar K",
    designation: "Asst. Professor",
    department: "Chemistry",
    color: "saffron",
    summary: "Assistant chemistry faculty focused on teaching and research.",
  },
  {
    name: "Dr. C Prathibha",
    designation: "Associate Professor",
    department: "Physics",
    color: "basil",
    summary: "Associate professor in physics with a focus on experimental science.",
  },
  {
    name: "Dr. V Sai Muthukumar",
    designation: "Asst. Professor",
    department: "Physics",
    color: "plum",
    summary: "Assistant physics professor teaching core physics subjects.",
  },
  {
    name: "Dr. R Dharmaraj",
    designation: "Asst. Professor",
    department: "Physics",
    color: "sage",
    summary: "Assistant professor in physics supporting student labs and courses.",
  },
  {
    name: "Dr. Rajabhushan Jagadish Nayak",
    designation: "Asst. Professor",
    department: "Economics",
    color: "pomegranate",
    summary: "Assistant professor teaching economics and social science topics.",
  },
  {
    name: "Dr. Siva Kiran Guptha K",
    designation: "Asst. Professor",
    department: "Economics",
    color: "turmeric",
    summary: "Assistant professor in economics and finance education.",
  },
  {
    name: "Dr. Muralikrishna Molli",
    designation: "Asst. Professor",
    department: "Physics",
    color: "saffron",
    summary: "Assistant physics professor teaching modern physics concepts.",
  },
  {
    name: "Dr. Dinesh Kumar Choudhury",
    designation: "Asst. Professor",
    department: "Economics",
    color: "basil",
    summary: "Assistant economics professor focusing on development and public economics.",
  },
  {
    name: "Sri Dharmendra Kalita",
    designation: "Asst. Professor",
    department: "Management & Commerce",
    color: "plum",
    summary: "Assistant professor in commerce and management education.",
  },
  {
    name: "Dr. Vedavathi Aluri",
    designation: "Asst. Professor",
    department: "Physics",
    color: "sage",
    summary: "Assistant physics professor teaching science courses.",
  },
  {
    name: "Dr. Gadige Paramesh",
    designation: "Asst. Professor",
    department: "Physics",
    color: "pomegranate",
    summary: "Assistant physics faculty engaged in teaching and research.",
  },
  {
    name: "Dr. Swarup Kundu",
    designation: "Asst. Professor",
    department: "Physics",
    color: "turmeric",
    summary: "Assistant professor teaching physics and laboratory subjects.",
  },
  {
    name: "Mrs. B Saisoujanya Kumari",
    designation: "Asst. Professor",
    department: "Education",
    color: "saffron",
    summary: "Assistant professor focusing on education and pedagogy.",
  },
  {
    name: "Dr. Malla Penchala Prasad",
    designation: "Asst. Professor",
    department: "Telugu Language & Literature",
    color: "basil",
    summary: "Assistant professor in Telugu language and literature studies.",
  },
  {
    name: "Mrs. P Padmambika",
    designation: "Asst. Professor",
    department: "Education",
    color: "plum",
    summary: "Assistant professor teaching education and learning theory.",
  },
  {
    name: "Dr. Lavanya Rathi P",
    designation: "Asst. Professor",
    department: "Physics",
    color: "sage",
    summary: "Assistant physics professor engaged in teaching and experiments.",
  },
  {
    name: "Dr. Manas Kandi",
    designation: "Asst. Professor",
    department: "Political Science",
    color: "pomegranate",
    summary: "Assistant professor teaching political theory and comparative politics.",
  },
  {
    name: "Dr. Ramya E M",
    designation: "Asst. Professor",
    department: "Biosciences",
    color: "turmeric",
    summary: "Assistant biosciences professor teaching cell and molecular biology.",
  },
  {
    name: "Sri Sreepada V Satya N Sarma",
    designation: "Asst. Professor",
    department: "Mathematics & Computer Science",
    color: "saffron",
    summary: "Assistant professor in mathematics and computer science.",
  },
  {
    name: "Prof. Ranga Reddy Burri",
    designation: "Professor of Practice",
    department: "Biosciences",
    color: "basil",
    summary: "Practice professor integrating industry biosciences with academic learning.",
  },
  {
    name: "Dr. Sreerangavani K",
    designation: "Asst. Professor",
    department: "Mathematics & Computer Science",
    color: "plum",
    summary: "Assistant professor in mathematics and computing applications.",
  },
  {
    name: "Sri Sai Prabhakar Balantrapu",
    designation: "Asst. Professor",
    department: "Economics",
    color: "sage",
    summary: "Assistant professor teaching economics and commerce.",
  },
  {
    name: "Dr. P Sunil Kumar",
    designation: "Asst. Professor",
    department: "Mathematics & Computer Science",
    color: "pomegranate",
    summary: "Assistant professor teaching mathematics and computer science.",
  },
  {
    name: "Dr. Srinath M S",
    designation: "Asst. Professor",
    department: "Mathematics & Computer Science",
    color: "turmeric",
    summary: "Assistant professor teaching mathematics and computational topics.",
  },
  {
    name: "Mrs. Gorle Santoshi Kumari",
    designation: "Asst. Professor",
    department: "Mathematics & Computer Science",
    color: "saffron",
    summary: "Assistant professor in mathematics and computing education.",
  },
  {
    name: "Dr. Prashant Luthra",
    designation: "Asst. Professor",
    department: "English Language & Literature",
    color: "basil",
    summary: "Assistant professor teaching English language and literature.",
  },
  {
    name: "Dr. Kurma Rao Tyada",
    designation: "Asst. Professor",
    department: "Mathematics & Computer Science",
    color: "plum",
    summary: "Assistant professor in mathematics and computing.",
  },
  {
    name: "Sri C N Kshetragna",
    designation: "Professor of Practice",
    department: "Management & Commerce",
    color: "sage",
    summary: "Practice professor with applied management and commerce expertise.",
  },
  {
    name: "Dr. K Vengata Krishnan",
    designation: "Asst. Professor",
    department: "Mathematics & Computer Science",
    color: "pomegranate",
    summary: "Assistant professor teaching mathematics and computer science.",
  },
  {
    name: "Dr. L Goverthanan",
    designation: "Professor of Practice",
    department: "Management & Commerce",
    color: "turmeric",
    summary: "Practice professor bringing industry-facing management insight.",
  },
  {
    name: "Dr. B Venkata Ramana",
    designation: "Asst. Professor",
    department: "English Language & Literature",
    color: "saffron",
    summary: "Assistant English faculty specialized in language and literature.",
  },
  {
    name: "Dr. Nelli Vani Sri",
    designation: "Asst. Professor",
    department: "English Language & Literature",
    color: "basil",
    summary: "Assistant professor teaching English literature and communication.",
  },
  {
    name: "Mrs. Aarthi R M",
    designation: "Asst. Professor",
    department: "English Language & Literature",
    color: "plum",
    summary: "Assistant professor in English language and literature education.",
  },
  {
    name: "Dr. Siddhartha R",
    designation: "Asst. Professor",
    department: "English Language & Literature",
    color: "sage",
    summary: "Assistant English faculty focused on literature and writing.",
  },
  {
    name: "Dr. Vijaya Lekshmi R",
    designation: "Asst. Professor",
    department: "English Language & Literature",
    color: "pomegranate",
    summary: "Assistant professor teaching English literature and communication.",
  },
  {
    name: "Dr. Santanu Bhattacharya",
    designation: "Asst. Professor",
    department: "Mathematics & Computer Science",
    color: "turmeric",
    summary: "Assistant professor in mathematics and computational education.",
  },
  {
    name: "Ms. Sai Archana M",
    designation: "Teaching Assistant",
    department: "English Language & Literature",
    color: "saffron",
    summary: "Teaching assistant supporting English language instruction.",
  },
  {
    name: "Sri Nishikant Barodekar",
    designation: "Asst. Professor (Tabla)",
    department: "Performing Arts",
    color: "basil",
    summary: "Tabla instructor and performing arts educator.",
  },
  {
    name: "Mrs. A Sujana",
    designation: "Asst. Professor",
    department: "Political Science",
    color: "plum",
    summary: "Assistant professor teaching political science and governance.",
  },
  {
    name: "Dr. V Prathyusha",
    designation: "Asst. Professor",
    department: "Chemistry",
    color: "sage",
    summary: "Assistant professor teaching chemistry and analytical science.",
  },
  {
    name: "Dr. A Sunil",
    designation: "Asst. Professor",
    department: "Chemistry",
    color: "pomegranate",
    summary: "Assistant professor in chemistry education and research.",
  },
  {
    name: "Sri Jagadeeswaran Sai Govardhan",
    designation: "Asst. Professor",
    department: "English Language & Literature",
    color: "turmeric",
    summary: "Assistant professor teaching English literature and communication.",
  },
  {
    name: "Dr. V N Ravi Kishore Vutukuri",
    designation: "Asst. Professor",
    department: "Chemistry",
    color: "saffron",
    summary: "Assistant professor teaching chemistry courses.",
  },
  {
    name: "Sri D Anantha Rao",
    designation: "Asst. Professor (Mridangam)",
    department: "Performing Arts",
    color: "basil",
    summary: "Mridangam instructor in performing arts and music education.",
  },
  {
    name: "Dr. Santanu Roy",
    designation: "Asst. Professor",
    department: "Chemistry",
    color: "plum",
    summary: "Assistant professor teaching chemistry and research methodology.",
  },
  {
    name: "Sri Raghavendra",
    designation: "Asst. Professor (Hindustani Vocal)",
    department: "Performing Arts",
    color: "sage",
    summary: "Hindustani vocal instructor in performing arts.",
  },
  {
    name: "Dr. A S Vishwanathan",
    designation: "Asst. Professor",
    department: "Biosciences",
    color: "pomegranate",
    summary: "Assistant biosciences professor teaching life science subjects.",
  },
  {
    name: "Dr. K K Sai Anand",
    designation: "Asst. Professor",
    department: "Biosciences",
    color: "turmeric",
    summary: "Assistant biosciences faculty engaged in research and teaching.",
  },
  {
    name: "Mrs. B Anusha",
    designation: "Asst. Professor",
    department: "Biosciences",
    color: "saffron",
    summary: "Assistant professor teaching biosciences and laboratory courses.",
  },
  {
    name: "Sri Sreenivasan P S",
    designation: "Asst. Professor (Ad hoc) Carnatic Vocal",
    department: "Performing Arts",
    color: "basil",
    summary: "Carnatic vocal instructor in performing arts.",
  },
  {
    name: "Dr. V N S Malleswara Kota D",
    designation: "Asst. Professor",
    department: "Biosciences",
    color: "plum",
    summary: "Assistant professor teaching bioscience and biotechnology topics.",
  },
  {
    name: "Sri J Saidath",
    designation: "Asst. Lecturer in Music (Mridangam)",
    department: "Performing Arts",
    color: "sage",
    summary: "Mridangam lecturer in performing arts.",
  },
  {
    name: "Sri Kanadia Jagdishkumar Harshadbhai",
    designation: "Asst. Professor (Ad hoc) (Tabla)",
    department: "Performing Arts",
    color: "pomegranate",
    summary: "Tabla instructor in performing arts.",
  },
  {
    name: "Sri R Mahesh Varma",
    designation: "Asst. Lecturer in Music (Veena)",
    department: "Performing Arts",
    color: "turmeric",
    summary: "Veena lecturer in performing arts.",
  },
  {
    name: "Dr. Sowmya Srinivasan",
    designation: "Asst. Professor",
    department: "English Language & Literature",
    color: "saffron",
    summary: "Assistant English faculty teaching literature and language.",
  },
  {
    name: "Dr. Balaram Khamari",
    designation: "Asst. Professor",
    department: "Biosciences",
    color: "basil",
    summary: "Assistant biosciences professor focused on life science education.",
  },
  {
    name: "Dr. Shalini",
    designation: "Asst. Professor",
    department: "Chemistry",
    color: "plum",
    summary: "Assistant chemistry professor teaching chemical sciences.",
  },
];

export const SCHOLARS = [
  "Ms. Ashrita C Haldipur",
  "Ms. Manjula Devi Ghoora",
  "Ms. N Saiharini",
  "Ms. Shrijana Rasaily",
  "Ms. Alisha Pradhan",
  "Ms. Sai Sruthi Shree K K",
  "Ms. Sai Dharshini S",
];
