export type PublicationType = "Journal Paper" | "Book Chapter" | "Book" | "Conference Proceedings" | "Other";

export type PublicationYearSummary = {
  year: string;
  ugcPapers: number;
  nonUgcPapers: number;
  totalPapers: number;
  books: number;
};

export type PublicationEntry = {
  id: string;
  year: string;
  type: PublicationType;
  title: string;
  authors: string;
  outlet: string;
  issn?: string;
  link?: string;
  ugcInfo?: string;
  note?: string;
};

export const PUBLICATION_SUMMARY: PublicationYearSummary[] = [
  { year: "2021", ugcPapers: 2, nonUgcPapers: 0, totalPapers: 2, books: 0 },
  { year: "2020", ugcPapers: 3, nonUgcPapers: 7, totalPapers: 10, books: 0 },
  { year: "2019", ugcPapers: 1, nonUgcPapers: 2, totalPapers: 3, books: 3 },
  { year: "2018", ugcPapers: 3, nonUgcPapers: 4, totalPapers: 7, books: 0 },
  { year: "2017", ugcPapers: 1, nonUgcPapers: 4, totalPapers: 5, books: 1 },
  { year: "2016", ugcPapers: 1, nonUgcPapers: 6, totalPapers: 7, books: 6 },
  { year: "2015", ugcPapers: 0, nonUgcPapers: 2, totalPapers: 2, books: 1 },
];

export const PUBLICATIONS: PublicationEntry[] = [
  {
    id: "2015-01",
    year: "2015",
    type: "Journal Paper",
    title: "Phytoceuticals in aniseeds: A practical approach for isolation and identification",
    authors: "Shobha RI and Andallu B",
    outlet: "International Journal of Bioassays",
    issn: "2278-778X",
    link: "https://www.google.com/search?q=Phytoceuticals+in+aniseeds+International+Journal+of+Bioassays",
    note: "Not listed in UGC CARE list",
  },
  {
    id: "2015-02",
    year: "2015",
    type: "Journal Paper",
    title: "Phytoconstituents and antimicrobial activity of aniseeds (Pimpinella anisum L.)",
    authors: "Shobha RI and Andallu B",
    outlet: "Ewemen Journal of Microbial Research",
    issn: "2488-9148",
    link: "https://www.google.com/search?q=Phytoconstituents+and+antimicrobial+activity+of+aniseeds+Ewemen+Journal+of+Microbial+Research",
    note: "Not listed in UGC CARE list",
  },
  {
    id: "2016-01",
    year: "2016",
    type: "Journal Paper",
    title: "Postharvest quality and shelf life of fresh-cut fenugreek (Trigonella foenum-graecum L.) leaves: Impact of packaging and Aloe vera gel coating",
    authors: "N. Srividya and Manjula D. Ghoora",
    outlet: "International Journal of Nutrition and Agriculture Research",
    issn: "2393-9540",
    link: "https://www.google.com/search?q=Postharvest+quality+and+shelf+life+of+fresh-cut+fenugreek+leaves",
    note: "Not listed in UGC CARE lists",
  },
  {
    id: "2016-02",
    year: "2016",
    type: "Journal Paper",
    title: "Effect of inulin, fructooligosaccharides and L. acidophilus in formulating a synbiotic yogurt",
    authors: "K. Sudha Rani and N. Srividya",
    outlet: "Asian Journal of Dairy and Food Research",
    issn: "0971-4456",
    link: "https://www.google.com/search?q=Effect+of+inulin+fructooligosaccharides+and+L.+acidophilus+in+formulating+a+synbiotic+yogurt",
    note: "Not listed in UGC CARE list",
  },
  {
    id: "2016-03",
    year: "2016",
    type: "Journal Paper",
    title: "Nutritional Status of adolescents from Anantapur in South India",
    authors: "Meera M and V. Sreedevi",
    outlet: "International Journal of Nutrition and Agriculture Research",
    issn: "2393-9540",
    link: "https://www.google.com/search?q=Nutritional+Status+of+adolescents+from+Anantapur+in+South+India",
    note: "Not listed in UGC CARE list",
  },
  {
    id: "2016-04",
    year: "2016",
    type: "Journal Paper",
    title: "Nutritional status assessment and evaluation of educational effectiveness of nutritional games approach in adolescents",
    authors: "M. Meera, R. K. Anuradha and V. Sreedevi",
    outlet: "International Journal of Medicine and Health Profession Research",
    issn: "2394-7403",
    link: "https://www.google.com/search?q=Nutritional+status+assessment+and+evaluation+of+educational+effectiveness+of+nutritional+games+approach",
    note: "Not listed in UGC CARE list",
  },
  {
    id: "2016-05",
    year: "2016",
    type: "Journal Paper",
    title: "Efficacy of nutritional games to improve learning of nutritional knowledge in adolescents",
    authors: "M. Meera, R. K. Anuradha and V. Sreedevi",
    outlet: "International Journal of Nutrition and Agriculture Research",
    issn: "2393-9540",
    link: "https://www.google.com/search?q=Efficacy+of+nutritional+games+to+improve+learning+of+nutritional+knowledge+in+adolescents",
    note: "Not listed in UGC CARE list",
  },
  {
    id: "2016-06",
    year: "2016",
    type: "Journal Paper",
    title: "Evaluation of green solvents for a sustainable zein extraction from ethanol industry DDGS",
    authors: "J Gupta, BW Wilson, PV Vadlani",
    outlet: "Biomass and Bioenergy",
    issn: "0961-9534",
    link: "https://aulibrary.avinuty.ac.in/pdf/UGC_List_of_Journals.pdf",
    ugcInfo: "UGC Serial No. 2996 and Journal No. 14753",
  },
  {
    id: "2017-01",
    year: "2017",
    type: "Journal Paper",
    title: "Storage effects on phytochemicals, antioxidant activity and sensory quality of fenugreek (Trigonella foenum-graecum L.) microgreens and mature leaves",
    authors: "Manjula D. Ghoora and N. Srividya",
    outlet: "International Journal of Food and Nutritional Sciences",
    issn: "2167-0434",
    link: "https://www.google.com/search?q=Storage+effects+on+phytochemicals+antioxidant+activity+and+sensory+quality+of+fenugreek+microgreens",
    note: "Not listed in UGC CARE lists",
  },
  {
    id: "2017-02",
    year: "2017",
    type: "Journal Paper",
    title: "Impact of gamma irradiation and osmotic dehydration on quality characteristics of guava (Psidium guajava) slices",
    authors: "Srijaya M and Shanthipriya",
    outlet: "Asian Journal of Dairy & Food Research",
    issn: "0971-4456",
    link: "https://www.google.com/search?q=Impact+of+gamma+irradiation+and+osmotic+dehydration+on+quality+characteristics+of+guava+slices",
    note: "Not listed in UGC CARE lists",
  },
  {
    id: "2017-03",
    year: "2017",
    type: "Journal Paper",
    title: "To study the efficacy of modified hearth approach for adolescents",
    authors: "M. Meera, R. K. Anuradha and V. Sreedevi",
    outlet: "International Journal of Medicine and Health Profession Research",
    issn: "2394-7403",
    link: "https://www.google.com/search?q=To+study+the+efficacy+of+modified+hearth+approach+for+adolescents",
    note: "Not listed in UGC CARE lists",
  },
  {
    id: "2017-04",
    year: "2017",
    type: "Journal Paper",
    title: "Formulation and quality evaluation of agathi (Sesbania grandiflora (L.) Poir) leaves enriched pizza base a healthier substitute for the regular pizza base",
    authors: "A Sumana and M Aruna",
    outlet: "International Journal of Home Science",
    issn: "2395-7476",
    link: "https://www.google.com/search?q=Formulation+and+quality+evaluation+of+agathi+leaves+enriched+pizza+base",
    note: "Not listed in UGC CARE lists",
  },
  {
    id: "2017-05",
    year: "2017",
    type: "Journal Paper",
    title: "Functional quality, sensorial and shelf life characteristics of Agathi (Sesbania grandiflora (L). Poir leaves enriched breads",
    authors: "A Sumana and M Aruna",
    outlet: "Functional Foods in Health and Disease",
    issn: "2160-3855",
    link: "https://aulibrary.avinuty.ac.in/pdf/UGC_List_of_Journals.pdf",
    ugcInfo: "UGC Serial No. 8058 and Journal No. 45053",
  },
  {
    id: "2017-06",
    year: "2017",
    type: "Book Chapter",
    title: "Risk Analysis in Food Safety - An Overview",
    authors: "A. Sumana and Barbhai Mrunal D.",
    outlet: "Food Safety and Standards: Laws, Tools and Management Systems",
    note: "NIPA Genx Electronic Resources & Solutions P.Ltd, ISBN: 9789394490260",
  },
  {
    id: "2018-01",
    year: "2018",
    type: "Journal Paper",
    title: "Development of functional sapodilla flakes with neutraceutical and health regulatory components and their quality characteristics during storage",
    authors: "Dhanya K and Srijaya M.",
    outlet: "International Journal of Food and Nutritional Sciences",
    issn: "2319-1775",
    link: "https://www.google.com/search?q=Development+of+functional+sapodilla+flakes+with+neutraceutical+and+health+regulatory+components",
    note: "Not listed in UGC CARE lists",
  },
  {
    id: "2018-02",
    year: "2018",
    type: "Journal Paper",
    title: "Recent developments in osmotic dehydration technique for improving the post-harvest quality of fruits and vegetables",
    authors: "Keerthana HK and Srijaya M",
    outlet: "Research Journal of Pharmaceutical, Biological and Chemical Sciences",
    issn: "2572-2999",
    link: "https://www.google.com/search?q=Recent+developments+in+osmotic+dehydration+technique",
    note: "Not listed in UGC CARE lists",
  },
  {
    id: "2018-03",
    year: "2018",
    type: "Journal Paper",
    title: "Health enhancing properties of an edible flower Sesbania grandiflora (L.) poir (agathi) based processed product",
    authors: "A Sumana, E Sreedevi, M Aruna",
    outlet: "Indian Research Journal of Pharmacy and Science",
    issn: "2349-5332",
    link: "https://www.google.com/search?q=Health+enhancing+properties+of+an+edible+flower+Sesbania+grandiflora+based+processed+product",
    note: "Not listed in UGC CARE lists",
  },
  {
    id: "2018-04",
    year: "2018",
    type: "Journal Paper",
    title: "Consumer belief and attitude towards dark chocolates among Indian customers",
    authors: "Gayathri. S and Sumana A",
    outlet: "International Journal of Nutrition and Agricultural Research",
    issn: "2393-9540",
    link: "https://www.google.com/search?q=Consumer+belief+and+attitude+towards+dark+chocolates+among+Indian+customers",
    note: "Not listed in UGC CARE lists",
  },
  {
    id: "2018-05",
    year: "2018",
    type: "Journal Paper",
    title: "Extraction, characterisation and utilisation of passion fruit peel pectin.",
    authors: "N.Saiharini and A.Padmaja",
    outlet: "Asia Journal of Multidimensional Research",
    issn: "2278-4853",
    link: "https://aulibrary.avinuty.ac.in/pdf/UGC_List_of_Journals.pdf",
    ugcInfo: "Approved Journal No. 47638 in UGC CARE list; discontinued from the list from Feb 2020",
  },
  {
    id: "2018-06",
    year: "2018",
    type: "Journal Paper",
    title: "Effectiveness of different myoglobin states to minimize high pressure induced discoloration in raw ground beef",
    authors: "J Gupta, CG Bower, GA Cavender, GA Sullivan",
    outlet: "LWT-Food Science and Technology",
    issn: "0023-6438",
    link: "https://aulibrary.avinuty.ac.in/pdf/UGC_List_of_Journals.pdf",
    ugcInfo: "UGC Serial No.16952 and Journal No. 5648",
  },
  {
    id: "2018-07",
    year: "2018",
    type: "Journal Paper",
    title: "Effect of differing ingredients and packaging technologies on the color of high pressure processed ground beef",
    authors: "J Gupta, CG Bower, GA Sullivan, GA Cavender",
    outlet: "Journal of Food Quality",
    issn: "0146-9428",
    link: "https://aulibrary.avinuty.ac.in/pdf/UGC_List_of_Journals.pdf",
    ugcInfo: "UGC Serial No.13770 and Journal No. 7618",
  },
  {
    id: "2019-01",
    year: "2019",
    type: "Journal Paper",
    title: "Micro farming of greens: A viable enterprise for enhancing economic, food and nutritional security of farmers",
    authors: "Manjula D. Ghoora and N. Srividya",
    outlet: "International Journal of Nutrition and Agriculture Research",
    issn: "2393-9540",
    link: "https://www.google.com/search?q=Micro+farming+of+greens+a+viable+enterprise",
    note: "Not listed in UGC CARE list",
  },
  {
    id: "2019-02",
    year: "2019",
    type: "Journal Paper",
    title: "Innovative zein extraction from distillers' grains with solubles: Process development and product characterization studies",
    authors: "J Gupta, PV Vadlani, CS Lau, RL Madl, YC Shi",
    outlet: "Environmental Progress and Sustainable Energy",
    issn: "1944-7450",
    link: "https://aulibrary.avinuty.ac.in/pdf/UGC_List_of_Journals.pdf",
    ugcInfo: "UGC Serial No. 6886 and Journal No. 19822",
  },
  {
    id: "2020-01",
    year: "2020",
    type: "Journal Paper",
    title: "In vitro glycemic response of indigenous pigmented rice cultivars from South India and influence of different carbohydrate components",
    authors: "Ashrita C. Haldipur and N. Srividya",
    outlet: "Current Research in Nutrition and Food Science",
    issn: "2347-467X",
    link: "https://mjl.clarivate.com/search-results?issn=2347-467X&hide_exact_match_fl=true&utm_source=mjl&utm_medium=share-by-link&utm_campaign=search-results-share-this-journal",
  },
  {
    id: "2020-02",
    year: "2020",
    type: "Journal Paper",
    title: "Effect of packaging and coating technique on postharvest quality and shelf life of Raphanus sativus and Hibiscus sabdariffa L. microgreens",
    authors: "Manjula D. Ghoora & N. Srividya",
    outlet: "Foods",
    issn: "2304-8158",
    link: "https://mjl.clarivate.com/search-results",
    note: "Web of Science link via UGC CARE list portal",
  },
  {
    id: "2020-03",
    year: "2020",
    type: "Journal Paper",
    title: "Nutrient composition, oxalate content and nutritional ranking of ten culinary microgreens",
    authors: "Manjula D. Ghoora, D. R. Babu, N. Srividya",
    outlet: "Journal of Food Composition and Analysis",
    issn: "0889-1575",
    link: "https://aulibrary.avinuty.ac.in/pdf/UGC_List_of_Journals.pdf",
    ugcInfo: "UGC Serial No. 13763 and Journal No. 7609",
  },
  {
    id: "2020-04",
    year: "2020",
    type: "Journal Paper",
    title: "Comparative evaluation of phytochemical content, antioxidant capacities and overall antioxidant potential of select culinary microgreens",
    authors: "Manjula D. Ghoora, Ashrita. C. Haldipur, & N. Srividya",
    outlet: "Journal of Agriculture and Food Research",
    issn: "2666-1543",
    note: "Not listed in UGC CARE list",
  },
  {
    id: "2021-01",
    year: "2021",
    type: "Journal Paper",
    title: "Indian red rice phenolic metabolites as potential natural inhibitors of SARS-CoV-2 main protease: A metabolomic and in silico study",
    authors: "Shrijana Rasaily, Ashrita C. Haldipur and N. Srividya",
    outlet: "Annals of Phytomedicine",
    issn: "2393-9885",
    link: "http://dx.doi.org/10.21276/ap.2021.10.1",
  },
  {
    id: "2021-02",
    year: "2021",
    type: "Journal Paper",
    title: "A comparative evaluation of in vitro antihyperglycemic potential of Bamboo seed rice (Bambusa arundinacea) and Garudan samba (Oryza sativa): An integrated metabolomics, enzymatic and molecular docking approach",
    authors: "Ashrita C. Haldipur and N. Srividya",
    outlet: "Journal of Cereal Science",
    issn: "0733-5210",
    link: "https://www.sciencedirect.com/science/article/abs/pii/S0733521021000412",
  },
  {
    id: "2021-03",
    year: "2021",
    type: "Journal Paper",
    title: "Multi-mechanistic in vitro evaluation of antihyperglycemic, antioxidant and antiglycation activities of three phenolic-rich Indian red rice genotypes and in silico evaluation of their phenolic metabolites",
    authors: "Ashrita C. Haldipur & N. Srividya",
    outlet: "Foods",
    issn: "2311-5637",
    link: "http://dx.doi.org/10.3390/foods10112818",
  },
  {
    id: "2022-01",
    year: "2022",
    type: "Journal Paper",
    title: "Studies on nutrient and phytochemical composition and assessment of in vitro antioxidant and enzyme inhibitory properties of watermelon fruit by-products",
    authors: "N. Saiharini and A. Padmaja",
    outlet: "Annals of Phytomedicine",
    issn: "2393-9885",
    link: "http://dx.doi.org/10.54085/ap.2022.11.1.48",
  },
  {
    id: "2022-02",
    year: "2022",
    type: "Book Chapter",
    title: "Risk analysis in food safety- An overview",
    authors: "Sumana A. & Barbhai Mrunal D.",
    outlet: "Food Safety And Standards: Laws, Tools And Management Systems",
    note: "Nipa Genx Electronic Resources & Solutions P.Ltd, ISBN: 9789394490260",
  },
  {
    id: "2023-01",
    year: "2023",
    type: "Journal Paper",
    title: "Plant foods and their phytochemicals as DPP IV and PTP 1B inhibitors for blood glucose regulation: A review",
    authors: "N. Srividya, Ashrita C. Haldipur and Carani B. Sanjeevi",
    outlet: "Journal of Indian Institute of Science, Special issue",
    link: "https://doi.org/10.1007/s41745-023-00371-y",
  },
  {
    id: "2023-02",
    year: "2023",
    type: "Journal Paper",
    title: "Impact of COVID-19 pandemic lockdown on post-harvest management of fruits and vegetables in three districts of Andhra Pradesh",
    authors: "Sravani G., Sai Supriya, Lazima R., Alisha P., Srijaya M.",
    outlet: "Journal of Postharvest Technology",
    link: "http://jpht.in/MenuscriptFile/5012a8a0-1be8-4ac4-8f0f-169a0e7473ab.pdf",
  },
  {
    id: "2023-03",
    year: "2023",
    type: "Journal Paper",
    title: "Extraction And Characterization Of Pectin From Watermelon By-Products",
    authors: "N. Saiharini and A. Padmaja",
    outlet: "International Journal of Food and Nutritional Sciences",
    issn: "2320-7876",
    link: "https://doi.org/10.48047/IJFANS/V11/I7/52",
  },
  {
    id: "2023-04",
    year: "2023",
    type: "Journal Paper",
    title: "Food quality during Covid-19 pandemic in south India: Consumer survey and DART (Detect Adulteration with Rapid Test) Analyses",
    authors: "Katta Sanvika, Bollu Sai Sruthi and Jhinuk Gupta",
    outlet: "International Journal of Food and Nutritional Sciences",
    link: "https://doi.org/10.18805/jcdr.2022.23/11/2022",
  },
  {
    id: "2023-05",
    year: "2023",
    type: "Book",
    title: "Antioxidant potential of ajwain (Trachyspermum ammi L.) seeds and oil",
    authors: "Ashrita CH & Andallu B",
    outlet: "LAP LAMBERT Academic Publishing GmbH & Co. KG Germany",
    note: "ISBN: 978-620-5-49583-4",
  },
  {
    id: "2023-06",
    year: "2023",
    type: "Book",
    title: "Evaluation of Trachyspermum ammi L. for medicinal properties",
    authors: "Mekha MS & Andallu B",
    outlet: "LAP LAMBERT Academic Publishing GmbH & Co. KG Germany",
  },
  {
    id: "2023-07",
    year: "2023",
    type: "Book Chapter",
    title: "Dietary interventions to combat obesity in metabolic syndrome - Role of time restricted eating",
    authors: "N. Srividya, Ashrita C. Haldipur and Carani B. Sanjeevi",
    outlet: "Metabolic Syndrome",
    note: "In: Satinath Mukhopadhyay & Sunetra Mondal (Eds.), Elsevier, USA (In press)",
  },
  {
    id: "2023-08",
    year: "2023",
    type: "Book Chapter",
    title: "Risk Analysis in Food Safety - An Overview",
    authors: "A. Sumana and Barbhai Mrunal D.",
    outlet: "Food Safety and Standards: Laws, Tools and Management Systems",
    note: "In: New India Publishing Agency - NIPA, India",
  },
  {
    id: "2024-01",
    year: "2024",
    type: "Book",
    title: "Evaluation of Trachyspermum ammi L. for medicinal properties",
    authors: "Mekha M. S. & Andallu B.",
    outlet: "LAP LAMBERT Academic Publishing GmbH & Co. KG Germany",
    note: "ISBN-13: 9786206150367",
  },
  {
    id: "2024-02",
    year: "2024",
    type: "Book Chapter",
    title: "Lifestyle modifications and nutritional modulation of the immune system for prevention and management of diabetes mellitus: Current perspectives",
    authors: "Srividya N., Haldipur A. C., & Yerra H.",
    outlet: "Biochemical Immunology of Diabetes and Associated Complications",
    note: "Academic Press, ISBN:978-0-443-13195-0",
    link: "https://doi.org/10.1016/C2022-0-02117-6",
  },
  {
    id: "2024-03",
    year: "2024",
    type: "Book Chapter",
    title: "Dietary interventions to combat obesity in metabolic syndrome - Role of time restricted eating",
    authors: "Srividya N., Haldipur A. C., & Sanjeevi C. B.",
    outlet: "Metabolic Syndrome",
    note: "Academic Press, ISBN:978-0-323-85732-1",
    link: "https://doi.org/10.1016/C2020-0-02822-7",
  },
  {
    id: "2024-04",
    year: "2024",
    type: "Book Chapter",
    title: "Novel Technologies for Shelf-Life Extension of Food Products as a Competitive Advantage: A Review",
    authors: "Lohita B. and Srijaya M.",
    outlet: "Food Production, Diversity, and Safety Under Climate Change",
    note: "Springer, Cham. ISBN: 978-3-031-51646-7",
    link: "https://doi.org/10.1007/978-3-031-51647-4_24",
  },
  {
    id: "2024-05",
    year: "2024",
    type: "Book Chapter",
    title: "Fresh Fruits and Vegetables Quality and Safety: A Deep Insight on the Benefits of an Organic Farming Approach",
    authors: "Pradhan A. and Srijaya M.",
    outlet: "Food Production, Diversity, and Safety Under Climate Change",
    note: "Springer, Cham. ISBN: 978-3-031-51646-7",
    link: "https://doi.org/10.1007/978-3-031-51647-4_11",
  },
  {
    id: "2024-06",
    year: "2024",
    type: "Journal Paper",
    title: "Impact of onion-based interventions on biomarkers of diabetes and its complications in diabetic rats - A systematic review",
    authors: "Pandey M., Pathri M., Labani S. & N. Srividya",
    outlet: "Diabetes Research and Clinical Practice",
    link: "https://doi.org/10.1016/j.diabres.2024.111512",
  },
  {
    id: "2024-07",
    year: "2024",
    type: "Journal Paper",
    title: "Extraction, Estimation And Utilization Of Curry Leaf (Murraya Koenigii) Stalks As A Potential Source Of Antioxidants",
    authors: "Padmaja A.",
    outlet: "Asian Journal of Dairy and Food Research",
    link: "https://arccjournals.com/journal/asian-journal-of-dairy-and-food-research/DR-2111",
    note: "DOI: 10.18805/ajdfr.DR-2111",
  },
  {
    id: "2024-08",
    year: "2024",
    type: "Journal Paper",
    title: "Evaluation of chemical composition, antioxidant and anti-inflammatory potential of herbs enriched plant-based protein mix for women athletes",
    authors: "Tapasya Anand and Sparsh Sumnirom Subba",
    outlet: "Journal of Sports Science and Nutrition",
    link: "https://doi.org/10.33545/27077012.2024.v5.i2a.261",
  },
  {
    id: "2024-09",
    year: "2024",
    type: "Journal Paper",
    title: "Significance of Food Security and Safety behind India’s Sustainable Urban Development",
    authors: "Gupta J.",
    outlet: "International Journal of Nutritions",
    link: "https://journals.stmjournals.com/ijn/article=2024/view=135498/",
  },
  {
    id: "2024-10",
    year: "2024",
    type: "Journal Paper",
    title: "Investigation of Hazardous Food Additives in Indian Packaged Pickles through Chemical and Spectrophotometric Analyses",
    authors: "Vandana M., Rai N., Mounika S. & Gupta J.",
    outlet: "Journal of Chemical Health Risks",
    link: "https://jchr.org/index.php/JCHR/article/view/1133",
  },
  {
    id: "2024-11",
    year: "2024",
    type: "Journal Paper",
    title: "Effect of popping and milling on physical, chemical, structural, thermal properties and angle of repose of amaranth seed (Amaranthus cruentus L.) and finger millet (Eleusine coracana L. Gaertn) from Udhagamandalam",
    authors: "Sai Dharshini S. & Meera M.",
    outlet: "Applied Food Research",
    link: "https://doi.org/10.1016/j.afres.2023.100306",
  },
  {
    id: "2024-12",
    year: "2024",
    type: "Journal Paper",
    title: "Millet bars-healthier alternative to cereal bars: A review",
    authors: "Sai Dharshini S. & Meera M.",
    outlet: "Agricultural Reviews",
    link: "http://dx.doi.org/10.18805/ag.R-2229",
  },
  {
    id: "2024-13",
    year: "2024",
    type: "Journal Paper",
    title: "Glycemic response to high amylose, fibre-rich red rice meals and in vitro antihyperglycemic properties of prebiotic enriched fermented red rice beverage",
    authors: "Srividya N. & Haldipur A.C.",
    outlet: "Clinical Nutrition ESPEN",
    link: "https://doi.org/10.1016/j.clnesp.2024.07.692",
  },
  {
    id: "2024-14",
    year: "2024",
    type: "Journal Paper",
    title: "Dietary mineral contribution and mineral quality rating of ten culinary microgreens grown in cocopeat vs. compost-enriched soil",
    authors: "Srividya N. & Ghoora M.D.",
    outlet: "Clinical Nutrition ESPEN",
    link: "https://doi.org/10.1016/j.clnesp.2024.07.212",
  },
  {
    id: "2024-15",
    year: "2024",
    type: "Journal Paper",
    title: "Mislabeling in Indian Branded Health Foods: Case Study with Immunity Booster Food and Protein Supplement",
    authors: "Jhinuk Gupta, Shreya P Sarathy, Tharani Lakshmi Tharuni, Amrita Shaw",
    outlet: "International Journal of Nutritions",
    link: "https://journals.stmjournals.com/ijn/article=2024/view=181880/",
  },
  {
    id: "2024-16",
    year: "2024",
    type: "Journal Paper",
    title: "Revolutionizing nutrition: Exploring the transformative impact of amaranth integration on composite millet flakes",
    authors: "Dharshini S. S., Sudha M. L., & Meera M.",
    outlet: "Food and Humanity",
    link: "https://doi.org/10.1016/j.foohum.2024.100421",
  },
  {
    id: "2024-17",
    year: "2024",
    type: "Journal Paper",
    title: "Assessment of postharvest quality attributes and storability of sweet lime (Citrus limonia) var. Rangpur: a comparative investigation of conventional and indigenous organic cultivation in Andhra Pradesh, India",
    authors: "Pradhan A., Srijaya M.",
    outlet: "Organic Agriculture",
    link: "https://doi.org/10.1007/s13165-024-00475-4",
  },
  {
    id: "2024-18",
    year: "2024",
    type: "Journal Paper",
    title: "Chemical Composition, Anti-oxidant and Anti-diabetic Potential of Unexplored Ethnic Wild Edible Mushrooms of the Darjeeling Himalayan Hill Region, North West Bengal, India",
    authors: "Tapasya Anand, Gracy Rai and Shrijana R.",
    outlet: "International Journal of Research and Analytical Reviews",
    issn: "2348-1269",
    link: "http://doi.one/10.1729/Journal.40578",
  },
  {
    id: "2024-19",
    year: "2024",
    type: "Journal Paper",
    title: "Inhibition of proliferation of human osteosarcoma cell line (MG63) by ajwain (Trachyspermum ammi L.) plant extract",
    authors: "Anusha B, Darshan VMD and Andallu B.",
    outlet: "Current Botany",
    link: "https://doi.org/10.25081/cb.2024.v15.8673",
  },
  {
    id: "2024-20",
    year: "2024",
    type: "Journal Paper",
    title: "Distribution of unexplored ethnic wild edible mushrooms of the Darjeeling Himalayan hill region, North West Bengal, India",
    authors: "Tapasya Anand, Ms. Gracy Rai, Ms. Shrijana R.",
    outlet: "International Journal of Current Science",
    issn: "2250-1770",
    link: "https://rjpn.org/ijcspub/papers/IJCSP24C1023.pdf",
  },
  {
    id: "2024-21",
    year: "2024",
    type: "Journal Paper",
    title: "Nutrition care process: Continuity of care",
    authors: "Verma S. & Sumana A.",
    outlet: "International Journal of Research and Analytical Reviews",
    link: "https://www.ijrar.org",
  },
  {
    id: "2025-01",
    year: "2025",
    type: "Journal Paper",
    title: "LC-Q-TOF-MS phenolic profiling, data mining for antiviral compounds, and in-silico analysis against SARS-CoV-2 in heritage-pigmented rice metabolomes",
    authors: "Shrijana Rasaily, Ashrita CH, and N. Srividya",
    outlet: "Food Bioscience",
    link: "https://doi.org/10.1016/j.fbio.2024.105613",
  },
  {
    id: "2025-02",
    year: "2025",
    type: "Journal Paper",
    title: "Nutritional support for managing diabetic chronic leg ulcers in South India – A case report",
    authors: "Verma S. & Sumana A.",
    outlet: "International Journal of Nutrition and Dietetics",
    link: "https://doi.org/10.17654/2347527725001",
  },
  {
    id: "2025-03",
    year: "2025",
    type: "Journal Paper",
    title: "Extraction and Characterization of Dietary Fiber, Starch and Cellulose Microfibers from Field Bean and Cowpea Pods",
    authors: "Maddi Harika Sai, Thokada Rohini Kumari, Umapathi Naga Vinitha, Nimisha P and A. Padmaja",
    outlet: "International Journal of Scientific Research in Engineering and Management (IJSREM)",
    link: "https://ijsrem.com/volume09issue02february2025/",
    note: "DOI: 10.55041/IJSREM41720",
  },
  {
    id: "2025-04",
    year: "2025",
    type: "Journal Paper",
    title: "Knowledge, attitudes, and practices regarding iron deficiency anemia and probiotics among adolescent girls in Anantapur, India: A QIDAP-guided cross-sectional study",
    authors: "Sparsh Sumnirom Subba and Sumana Araveti",
    outlet: "Food and Humanity",
    link: "https://doi.org/10.1016/j.foohum.2025.100551",
  },
  {
    id: "2025-05",
    year: "2025",
    type: "Journal Paper",
    title: "Formulation and evaluation of functional foods for management of Metabolic dysfunction Associated Steatotic Liver Disease (MASLD)",
    authors: "K. Sai Lavanya, Sparsh Sumnirom Subba and Araveti Sumana",
    outlet: "International Journal of Nutrition and Dietetics",
    note: "PPH-3030-25059-IJND",
  },
  {
    id: "2025-06",
    year: "2025",
    type: "Journal Paper",
    title: "Optimized traditional breakfast recipes for MASLD: development and sensory evaluation",
    authors: "Annapoorna Sai Sathya V., Sparsh Sumnirom Subba and Araveti Sumana",
    outlet: "International Journal of Nutrition and Dietetics",
    note: "PPH-3029-25058-IJND",
  },
  {
    id: "2025-07",
    year: "2025",
    type: "Journal Paper",
    title: "A qualitative assessment of the impact of COVID-19 on the consumption, safety, and purchasing attributes of fruits and vegetables",
    authors: "Pradhan A., Srijaya M., Hegde M., Shaw A., Sreehitha D.",
    outlet: "Journal of Postharvest Technology",
    link: "https://doi.org/10.1016/j.foohum.2024.100421",
  },
  {
    id: "2025-08",
    year: "2025",
    type: "Journal Paper",
    title: "Glycemic response to high amylose, fibre-rich red rice meals and in vitro antihyperglycemic properties of prebiotic enriched fermented red rice beverage",
    authors: "Srividya N. & Haldipur A.C.",
    outlet: "Clinical Nutrition ESPEN",
    link: "https://doi.org/10.1016/j.clnesp.2024.07.692",
  },
  {
    id: "2025-09",
    year: "2025",
    type: "Journal Paper",
    title: "Dietary mineral contribution and mineral quality rating of ten culinary microgreens grown in cocopeat vs. compost-enriched soil",
    authors: "Srividya N. & Ghoora M.D.",
    outlet: "Clinical Nutrition ESPEN",
    link: "https://doi.org/10.1016/j.clnesp.2024.07.212",
  },
  {
    id: "2025-10",
    year: "2025",
    type: "Journal Paper",
    title: "Mislabeling in Indian Branded Health Foods: Case Study with Immunity Booster Food and Protein Supplement",
    authors: "Jhinuk Gupta, Shreya P Sarathy, Tharani Lakshmi Tharuni, Amrita Shaw",
    outlet: "International Journal of Nutritions",
    link: "https://journals.stmjournals.com/ijn/article=2024/view=181880/",
  },
  {
    id: "2025-11",
    year: "2025",
    type: "Journal Paper",
    title: "Revolutionizing nutrition: Exploring the transformative impact of amaranth integration on composite millet flakes",
    authors: "Dharshini S. S., Sudha M. L., & Meera M.",
    outlet: "Food and Humanity",
    link: "https://doi.org/10.1016/j.foohum.2024.100421",
  },
  {
    id: "2025-12",
    year: "2025",
    type: "Journal Paper",
    title: "Assessment of postharvest quality attributes and storability of sweet lime (Citrus limonia) var. Rangpur: a comparative investigation of conventional and indigenous organic cultivation in Andhra Pradesh, India",
    authors: "Pradhan A. and Srijaya M.",
    outlet: "Journal of Postharvest Technology",
    link: "https://doi.org/10.1007/s13165-024-00475-4",
  },
  {
    id: "2025-13",
    year: "2025",
    type: "Book",
    title: "Efficacy of coriander (Coriandrum sativum L.) seeds in combating oxidative stress in arthritis patients",
    authors: "Swetha Rani & Andallu B.",
    outlet: "LAP LAMBERT Academic Publishing GmbH & Co. KG Germany",
    note: "ISBN 978-620-6-15406-8",
    link: "https://www.exlibris.ch/de/buecher-buch/english-books/sweata-rani-rai/efficacy-of-coriander-seeds-in-combating-oxidative-stress-in-art/id/9786206154068/",
  },
  {
    id: "2025-14",
    year: "2025",
    type: "Conference Proceedings",
    title: "A systematic approach to investigate labeling accuracy of commercially available Indian baby foods",
    authors: "Rishika Aravapally, Amrita Shaw, Bezawada Sree Sesha Sravanika, Jhinuk Gupta",
    outlet: "BIO Web of Conferences 178, 03009",
    issn: "2117-4458",
    link: "https://doi.org/10.1051/bioconf/202517803009",
  },
  {
    id: "2025-15",
    year: "2025",
    type: "Conference Proceedings",
    title: "Formulation & evaluation of plant-based RTU protein mix for athletes",
    authors: "Poojitha Gali, Pradeepthi Marri and Tapasya Anand",
    outlet: "BIO Web of Conferences 178, 02003",
    issn: "2117-4458",
    link: "https://doi.org/10.1051/bioconf/202517802003",
  },
];
